[project]
classifiers = ["Private :: Do Not Upload"]
name = "pkg1"
version = "0.6.0"
description = "One of the projects in the monorepo."
readme = "README.md"
authors = [
    { name = "artdotlis", email = "artdotlis@pm.me" }
]
requires-python = ">=3.13,<4"
dependencies = [
    "shared_utils",
]

[project.scripts]
pkg1 = "pkg1.main:run"

[tool.setuptools.packages.find]
where = ["src"]
include = ["pkg1"]

[build-system]
requires = ["uv_build>=0.8.22,<0.9.0"]
build-backend = "uv_build"

[tool.uv.sources]
shared_utils = {  workspace = true }

[tool.uv]
package = true
default-groups = []
