repos:
  ###################################### Poetry ###################################
- repo: https://github.com/python-poetry/poetry
  rev: 1.5.0
  hooks:
  - id: poetry-check
  - id: poetry-lock
  - id: poetry-export
    args: [-f, requirements.txt, --without-hashes, -o, requirements.txt]

    ###################################### Local ####################################
- repo: local
  hooks:
  - id: tox
    name: tox test
    entry: bash -c 'make runTests'
    language: system
    pass_filenames: false
  - id: docs
    name: mkdocs
    entry: bash -c 'make runDocs'
    language: system
    pass_filenames: false

  ###################################### Default ###################################
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
      # Identify invalid files
  - id: check-ast
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - id: pretty-format-json
    args: [--autofix]

      # git checks
  - id: check-merge-conflict
  - id: check-added-large-files
    exclude: tests/media/.+
  - id: detect-private-key
  - id: check-case-conflict

      # General quality checks
  - id: check-symlinks
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: mixed-line-ending
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
  - id: end-of-file-fixer
    exclude: requirements.txt

      ###################################### Python ##################################
      # Python checks
  - id: check-builtin-literals
  - id: check-docstring-first
  - id: debug-statements
  - id: fix-byte-order-marker

  # python formatter
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black

  # ruff linter
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.269
  hooks:
  - id: ruff

  # python mypy
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.3.0
  hooks:
  - id: mypy
    entry: bash -c 'mypy --install-types --non-interactive "$@"'

  # dead code
- repo: https://github.com/jendrikseipp/vulture
  rev: v2.7
  hooks:
  - id: vulture
  ###################################### INI/TOML/YAML ###########################
  # ini formatter
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.9.0
  hooks:
  - id: pretty-format-ini
    args: [--autofix]
  - id: pretty-format-toml
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix]

  ###################################### SpellChecker ############################
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.4
  hooks:
  - id: codespell
    additional_dependencies:
    - tomli

  ###################################### Shell ###################################
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.9.0.2
  hooks:
  - id: shellcheck

  ###################################### GIT #####################################
- repo: https://github.com/commitizen-tools/commitizen
  rev: 3.2.2
  hooks:
  - id: commitizen
