repos:
  ###################################### Poetry ###################################
- repo: https://github.com/python-poetry/poetry
  rev: 1.4.0
  hooks:
  - id: poetry-check
  - id: poetry-lock
  - id: poetry-export
    args: [-f, requirements.txt, -o, requirements.txt]

    ###################################### Local ####################################
- repo: local
  hooks:
  - id: tox
    name: tox test
    entry: bash -c 'make runTests'
    language: system
    pass_filenames: false
  - id: docs
    name: mkdocs
    entry: bash -c 'make runDocs'
    language: system
    pass_filenames: false

  ###################################### Default ###################################
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
      # Identify invalid files
  - id: check-ast
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - id: pretty-format-json
    args: [--autofix]

      # git checks
  - id: check-merge-conflict
  - id: check-added-large-files
    exclude: tests/media/.+
  - id: detect-private-key
  - id: check-case-conflict

      # General quality checks
  - id: check-symlinks
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: mixed-line-ending
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
  - id: end-of-file-fixer
    exclude: requirements.txt

      ###################################### Python ##################################
      # Python checks
  - id: check-builtin-literals
  - id: check-docstring-first
  - id: debug-statements
  - id: fix-byte-order-marker

  # python formatter
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
    args: [-l 90]

  # python imports
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.9.0
  hooks:
  - id: reorder-python-imports
    args: [--py311-plus]

  # new python style
- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.2
  hooks:
  - id: pyupgrade
    args: [--py311-plus]

  # python mypy
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.2.0
  hooks:
  - id: mypy
    entry: bash -c 'mypy --install-types --non-interactive --config-file configs/dev/mypy.ini "$@"'

  # python flake8
- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    additional_dependencies: [flake8-bugbear]
    entry: bash -c 'flake8 --config configs/dev/flake8.ini "$@"'

  # security
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.5
  hooks:
  - id: bandit
    args: [-c, pyproject.toml]
    additional_dependencies: [toml]

  # dead code
- repo: https://github.com/jendrikseipp/vulture
  rev: v2.7
  hooks:
  - id: vulture
  ###################################### INI/TOML/YAML ###########################
  # ini formatter
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.8.0
  hooks:
  - id: pretty-format-ini
    args: [--autofix]
  - id: pretty-format-toml
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix]

  ###################################### SpellChecker ############################
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.4
  hooks:
  - id: codespell
    additional_dependencies:
    - tomli

  ###################################### Shell ###################################
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.9.0.2
  hooks:
  - id: shellcheck
