# SPDX-FileCopyrightText: 2026 Artur Lissin
#
# SPDX-License-Identifier: CC0-1.0

services:
  deploy:
    build:
      context: .
      dockerfile: ./Dockerfile
      secrets:
        - env_file
      args:
        USERNAME: devu
        USER_UID: 1000
        USER_GID: 1000
        WORK_DIR: "/workspace"
        NODE_VERSION: ${NODE_VERSION}
        BIN_DEPLOY_PREP: ${BIN_DEPLOY_PREP}
        BIN_DEPLOY_REQ: ${BIN_DEPLOY_REQ}
        BIN_DEPLOY_HEALTH: ${BIN_DEPLOY_HEALTH}
        BIN_DEPLOY_ENTRY_PROD: ${BIN_DEPLOY_ENTRY_PROD}

secrets:
    env_file:
        file: ./.env
