[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.black]
line-length = 90
target-version = ["py311"]

[tool.codespell]
count = ''
ignore-words = "configs/dev/ignore.txt"
quiet-level = 3
skip = '.mypy,.mypy_cache,.vscore,.tox,*~,*.cache,*.lock,venv,*ignore.txt'

[tool.commitizen]
major_version_zero = true
name = "cz_conventional_commits"
tag_format = "v$version"
update_changelog_on_bump = true
version_files = [
  "README.md:^\\[!\\[release:"
]
version_provider = "poetry"
version_type = "semver"

[tool.mypy]
allow_redefinition = false
# misc
allow_untyped_globals = false
check_untyped_defs = false
disallow_any_decorated = true
disallow_any_explicit = false
# any
disallow_any_expr = false
disallow_any_generics = true
disallow_any_unimported = false
disallow_incomplete_defs = true
disallow_subclassing_any = false
# functions
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
exclude = [
  "__pycache__",
  "\\.tox",
  "\\.mypy_cache",
  "venv"
]
ignore_missing_imports = true
implicit_reexport = true
local_partial_types = true
# none
no_implicit_optional = false
strict_equality = true
strict_optional = true
warn_no_return = true
# warn
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_ignores = true

[tool.poetry]
authors = [
  "Artur Lissin <artdotlis@pm.me>"
]
description = """Initial bare-bone Python project."""
include = [
  {path = "configs/src_ex/*", format = "sdist"},
  "src/knacr/py.typed"
]
keywords = ["python", "skeleton"]
license = "The Unlicense"
name = "initpy"
packages = [
  {include = "initpy", from = "src"}
]
readme = "README.md"
repository = "https://github.com/artdotlis/INITpy"
version = "0.2.0"

[tool.poetry.dependencies]
python = ">=3.11,<4"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
commitizen = ">=3.12,<4"
mypy = ">=1.7,<2"
pre-commit = ">=3.5,<4"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
mkdocs = ">=1.5,<2"
mkdocs-material = ">=9.4,<10"
mkdocstrings = ">=0.23,<1"
mkdocstrings-python = ">=1.7,<2"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
coverage = ">= 7.3,<8"
pytest = ">= 7.4,<8"
tox = ">=4.11,<5"

[tool.ruff]
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
exclude = [
  ".git",
  ".mypy_cache",
  ".ruff_cache",
  ".tox",
  ".venv",
  "__pypackages__",
  "__pycache__",
  "build",
  "dist",
  "venv"
]
fixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]
ignore = ["TRY003", "N818"]
line-length = 90
select = ["E", "F", "B", "C90", "S", "PT", "ARG", "PTH", "TRY", "RUF", "N"]
target-version = "py311"
unfixable = []

[tool.ruff.mccabe]
max-complexity = 11

[tool.ruff.pylint]
max-args = 8

[tool.vulture]
exclude = []
ignore_decorators = []
ignore_names = []
make_whitelist = true
min_confidence = 90
paths = ["src"]
sort_by_size = true
verbose = true
