site_name: INIT - Python
theme:
  name: material
plugins:
- search
- autorefs
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [../../src]
        options:
          show_submodules: true
markdown_extensions:
- abbr
- attr_list
- md_in_html
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- toc:
    toc_depth: 2
    permalink: '#'
    baselevel: 1
    separator: _
docs_dir: ../../docs
nav:
- Home: index.md
- Reference: ref/ref_m.md
- About: about.md
- License: license.md
