# SPDX-FileCopyrightText: 2026 Artur Lissin
#
# SPDX-License-Identifier: CC0-1.0

services:
  dev:
    user: devu
    env_file:
      - .env
    environment:
      HISTFILE: /dev/null
      HISTSIZE: 0
      HISTFILESIZE: 0
      EDITOR: vim
      SSH_AUTH_SOCK: /ssh-agent
    build:
      context: .
      dockerfile: configs/docker/dev.Dockerfile
      args:
        USERNAME: devu
        USER_UID: 1000
        USER_GID: 1000
        WORK_DIR: "/workspace"
        UV: ${UV_INSTALL_DIR}
        SSH_AUTH_SOCK: /ssh-agent
        BIN_DEPLOY_PREP: ${BIN_DEPLOY_PREP}
        BIN_DEPLOY_REQ: ${BIN_DEPLOY_REQ}
    volumes:
      - ${SSH_AUTH_SOCK:-/dev/null}:/ssh-agent:ro
      - .:/workspace:cached
      - ${GITCONFIG_PATH:-${HOME}/.gitconfig}:/etc/gitconfig:ro
    networks:
      - ollama
    ports:
      - ${DOC_PORT}:8000

networks:
    ollama:
        external: true
        name: ollama
        driver: bridge
