[project]
classifiers = ["Private :: Do Not Upload"]
name = "shared_utils"
version = "0.7.0"
description = "Shared library for packages."
readme = "README.md"
authors = [
    { name = "artdotlis", email = "artdotlis@pm.me" }
]
requires-python = ">=3.13,<4"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]
include = ["shared_utils"]

[build-system]
requires = ["uv_build>=0.8.22,<0.9.0"]
build-backend = "uv_build"

[tool.uv]
package = true
default-groups = []
