# SPDX-FileCopyrightText: 2026 Artur Lissin
#
# SPDX-License-Identifier: CC0-1.0

# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = ["prompt/**/*.md"]
precedence = "override"
SPDX-FileCopyrightText = "2026 Artur Lissin"
SPDX-License-Identifier = "CC0-1.0"
