[project]
classifiers = ["Private :: Do Not Upload"]
name = "utils"
version = "0.6.0"
description = "Shared library for packages."
readme = "README.md"
authors = [
    { name = "artdotlis", email = "artdotlis@pm.me" }
]
requires-python = ">=3.13.2"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
package = true
