name: main

on:
  pull_request:
  push:
    branches: [main]

jobs:
  mac_win_test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.13']
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r configs/dev/requirements.test.txt
        pip install .
        pip install tox
    - name: tox test
      run: |
        tox -e py
  lin_lint:
    env:
      PY_DIR: uv
      CU_HOME: /home/custom
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        sudo mkdir -p $CU_HOME && sudo chown runner -R $CU_HOME
        sudo apt install -y libedit-dev curl make git-lfs libsqlite3-dev libbz2-dev liblzma-dev
        curl -LsSf https://astral.sh/uv/install.sh | UV_INSTALL_DIR=$CU_HOME/$PY_DIR sh
        echo "$CU_HOME/$PY_DIR/bin" >> $GITHUB_PATH
        echo "$CU_HOME/$PY_DIR/shims" >> $GITHUB_PATH
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: lint and test
      run: |
        make dev
        make runChecks
